server:
  port: 8090

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    jdbc:
      dialect: postgresql

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351