server:
  port: 8093

spring:
  application:
    name: analytics-service

  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351